import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header/Header";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/app/_components/ui/dialog";
import { Button } from "@/app/_components/ui/button";
import OrderDesignProject from "@/app/_components/DesignProject/OrderDesignProject";
import { VisuallyHidden } from "radix-ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-avenir antialiased">
        <Header
          orderDesignProjectModalSlot={
            <Dialog>
              <DialogTrigger asChild>
                <Button className="w-fit">Заказать дизайн-проект</Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <VisuallyHidden.Root>
                    <DialogTitle>Заказать дизайн-проект</DialogTitle>
                  </VisuallyHidden.Root>
                  <OrderDesignProject />
                </DialogHeader>
              </DialogContent>
            </Dialog>
          }
        />
        <main className="pt-21 lg:pt-30">{children}</main>
      </body>
    </html>
  );
}
