import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header/Header";
import Footer from "@/app/_components/Footer/Footer";
import OrderDesignProjectModal from "@/app/_components/DesignProject/OrderDesignProjectModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-avenir antialiased">
        <Header orderDesignProjectModalSlot={<OrderDesignProjectModal />} />
        <main className="pt-21 lg:pt-30">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
